# Generated by Django 4.0.6 on 2023-01-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('closest_distance', models.IntegerField()),
                ('ndz_time', models.DateTimeField(verbose_name='Time NDZ Breached')),
            ],
        ),
    ]
